# Generated by Django 3.2.9 on 2021-11-09 09:11

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dna',
            name='chain',
            field=models.CharField(max_length=200, validators=[main.models.validate_DNA]),
        ),
    ]
